// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmzlvvbvidhtvcgqarou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtemx2dmJ2aWRodHZjZ3Fhcm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzQ5MDIsImV4cCI6MjA3MDk1MDkwMn0.ZPVm0jTehoXNw_3Hq3YfmPcj_FU7dlsGy8kV7HZK84A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});